I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 253, in script call
    call ch6_main
  File "game/script-ch6.rpy", line 5, in script call
    call ch61_main
  File "game/script.rpy", line 253, in script call
    call ch6_main
  File "game/script-ch6.rpy", line 5, in script call
    call ch61_main
ScriptError: could not find label 'ch61_main'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 253, in script call
    call ch6_main
  File "game/script-ch6.rpy", line 5, in script call
    call ch61_main
  File "renpy/ast.py", line 1444, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 253, in script call
    call ch6_main
  File "game/script-ch6.rpy", line 5, in script call
    call ch61_main
  File "renpy/script.py", line 910, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'ch61_main'.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
秋恋物语 1.0
Sun Aug  8 22:55:16 2021
